### PR TITLE
Fix web server crashing problem

### PR DESCRIPTION
**Pull request by developerbmw**
You forgot to allocate memory :)

### CODE REVIEW

**Comment by developerbmw** [comment]
You can't allocate a local variable of dynamic length...

**Comment by developerbmw** [comment]
Looks like this bug was introduced by this PR... 
https://github.com/codebox/bitmeteros/pull/12/files

**Comment by codebox** [comment]
My C is very rusty, I haven't looked at this code for years so tell me if you disagree, but this suggests you can create dynamic local arrays: http://gcc.gnu.org/onlinedocs/gcc/Variable-Length.html

**Comment by developerbmw** [comment]
My bad. You are right. Must have been thinking of C++.

I have updated the PR to use a local array.

**Comment by codebox** [comment]
Awesome, thanks!

**Pull request merged**
